dist: trusty
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - ./autogen.sh
  - ./configure
  - make
  - make test
notifications:
  irc:
    channels:
      - "chat.freenode.net#apertium"
  on_failure: change
  on_success: never
