.TH lt-print 1 2006-03-08 "" ""
.SH NAME
lt-print \- This application is part of the lexical processing modules
and tools (
.B lttoolbox
)
.PP
This tool is part of the apertium machine translation
architecture: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B lt-print
 bin_file
.PP
.SH DESCRIPTION
.BR lt-print
Is the application responsible for printing compiled dictionaries in
ATT format.
.PP
.B bin_file 
The compiled input file .
.PP
.B output_file
The transducer in ATT format .  

.SH SEE ALSO
.I lt-comp\fR(1),
.I lt-proc\fR(1),
.I lt-expand\fR(1),
.I apertium-tagger\fR(1),
.I apertium\fR(1).
.SH BUGS
Currently requires a UTF-8 locale (and doesn't crash if it doesn't have one).
.SH AUTHOR
(c) 2005--2016 Universitat d'Alacant / Universidad de Alicante. 
