.Dd March 8, 2006
.Dt LT-PRINT 1
.Os Apertium
.Sh NAME
.Nm lt-print
.Nd compiled dictionary printer for Apertium
.Sh SYNOPSIS
.Nm lt-print
.Ar bin_file
.Op Ar output_file
.Sh DESCRIPTION
.Nm lt-print
is the application responsible for printing compiled dictionaries in ATT format.
.Bl -tag -width Ds
.It Ar bin_file
The compiled input file.
.It Ar output_file
The transducer in ATT format.
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr apertium-tagger 1 ,
.Xr lt-comp 1 ,
.Xr lt-expand 1 ,
.Xr lt-proc 1
.Sh COPYRIGHT
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Currently requires a UTF-8 locale (and doesn't crash if it doesn't have one).
