.TH lt-trim 1 2006-03-08 "" ""
.SH NAME
lt-trim \- This application is part of the lexical processing modules
and tools (
.B lttoolbox
)
.PP
This tool is part of the apertium machine translation
architecture: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B lt-trim
analyser_file bidix_file output_file
.PP
.SH DESCRIPTION
.BR lt-trim
Is the application responsible for trimming compiled dictionaries.
The analyses (right-side) of analyser_file are trimmed to the
left-side of bidix_file.
.PP
.SH FILES
.B analyser_file
The untrimmed dictionary (a finite state transducer).
.PP
.B bidix_file
The dictionary to use to trim (a finite state transducer).
.PP
.B output_file
The trimmed dictionary (a finite state transducer).

.SH SEE ALSO
.I lt-comp\fR(1),
.I lt-proc\fR(1),
.I lt-trim\fR(1),
.I lt-expand\fR(1),
.I apertium-tagger\fR(1),
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
(c) 2005--2012 Universitat d'Alacant / Universidad de Alicante.
