.Dd March 8, 2006
.Dt LT-COMP 1
.Os Apertium
.Sh NAME
.Nm lt-tmxcomp
.Nd translation memories compiler for Apertium
.Sh SYNOPSIS
.Nm lt-tmxcomp
.Ar lang1 Ns - Ns Ar lang2
.Ar tmx_file
.Ar output_file
.Sh DESCRIPTION
.Nm lt-comp
is the application responsible for compiling translation memories in
the TMX format used by
.Xr lt-tmxproc 1
in Apertium into a compact and efficient representation
(a class of finite-state transducers called augmented letter transducers).
.Sh OPTIONS
.Bl -tag -width Ds
.It Ar lang1
Input language
.It Ar lang2
Output language
.El
.Sh FILES
.Bl -tag -width Ds
.It Ar tmx_file
The input translation memory, in TMX format.
.It Ar output_file
The compiled translation memory (a finite state transducer).
.El
.Sh SEE ALSO
.Xr apertium 1 ,
.Xr lt-tmxproc 1
.Sh AUTHOR
Copyright \(co 2005, 2006 Universitat d'Alacant / Universidad de Alicante.
This is free software.
You may redistribute copies of it under the terms of
.Lk https://www.gnu.org/licenses/gpl.html the GNU General Public License .
.Sh BUGS
Many... lurking in the dark and waiting for you!
