#! /bin/sh
FST=$1
CORPUS=$2
OUTPUT_FST=$3

# Temporary directory for intermediate files
TEMP_DIR=".tmp"
# Check if it exists
if ! [ -d "$TEMP_DIR" ]; then
	mkdir $TEMP_DIR
fi

CLEANED_CORPUS="$TEMP_DIR/clean-corpus.tagged"

ATTFST="$TEMP_DIR/transducer.att"
HFST_FST="$TEMP_DIR/transducer.hfst"

WEIGHTED_REGEXP="$TEMP_DIR/weighted-regex"
WEIGHTED_FST="$TEMP_DIR/weighted-pairs.hfst"
COMPOSED_FST="$TEMP_DIR/weighted-transducer.hfst"
SUBTRACTED_FST="$TEMP_DIR/subtracted-transducer.hfst"
DEFAULT_WEIGHTED_FST="$TEMP_DIR/default-weighted-transducer.hfst"
DISJUNCTED_FST="$TEMP_DIR/disjuncted-weighted-transducer.hfst"
DISJUNCTED_ATTFST="$TEMP_DIR/weighted-transducer.att"

# Convert the input FST to HFST
lt-print "$FST" | sed -e 's/:/\\:/' -e :a -e 's/ /@_SPACE_@/;ta'> $ATTFST

hfst-txt2fst --epsilon=ε -i $ATTFST -o $HFST_FST

# Clean the input tagged corpus
# REMOVE EMPTY LINES
sed -e '/^$/d' "$CORPUS" > $CLEANED_CORPUS

# Generate a weighted FST from the string pairs
LINES=$(wc -l $CLEANED_CORPUS | cut -d ' ' -f1)

sed -e 's/[ \t]//' -e 's/\^.*\///' -e 's/\$$//' $CLEANED_CORPUS > $WEIGHTED_REGEXP
python prepare_regex_strings.py $WEIGHTED_REGEXP
hfst-regexp2fst -j -i $WEIGHTED_REGEXP -o $WEIGHTED_FST

# Compose the input FST and the weighted FST
hfst-compose -1 $HFST_FST -2 $WEIGHTED_FST -v -o $COMPOSED_FST
hfst-subtract $HFST_FST $COMPOSED_FST -o $SUBTRACTED_FST
hfst-reweight -i $SUBTRACTED_FST -o $DEFAULT_WEIGHTED_FST -e -a 1000000
hfst-disjunct $DEFAULT_WEIGHTED_FST $COMPOSED_FST -o $DISJUNCTED_FST

# Compile the FST back using lttoolbox
lt-comp lr $DISJUNCTED_ATTFST $OUTPUT_FST

# Delete the temporary files
rm -rf "$TEMP_DIR"
